# Generated by Django 2.2.5 on 2020-02-27 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=1, max_length=180),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='seats',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
